name: Execução de testes do mapa

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  testes-mapa:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositorio
        uses: actions/checkout@v2

      - name: Setup C/C++ Compiler
        uses: rlalik/setup-cpp-compiler@v1.1
      
      - name: Install dependencies
        run: |
          sudo apt-get install libx11-dev xserver-xorg-dev xorg-dev
          sudo apt-get install libbsd-dev      

      - name: Compilando programa.
        run: make

      - name: compilando teste
        run: make test
        
      - name: rodando testes
        run: ./check_test
      
